### ISSUE TITLE
Set different color

### ISSUE THREAD

**Issue by keshavbhusal1** [keyrunHORNET/date_picker_converter#6]
How to set Holiday, festival day, etc are a different color.

**Comment by keyrunHORNET** [comment]
Try using setHighlightedDays()

On Sep 14, 2018 10:24, "Keshav Bhusal" <notifications@github.com> wrote:

How to set Holiday, festival day, etc are a different color.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/keyrunHORNET/date_picker_converter/issues/6>, or mute
the thread

**Comment by keshavbhusal1** [comment]
but how to change the color of setHighlightedDays().

**Comment by keyrunHORNET** [comment]
You cant right now.

Hopefully i will bring that feature soon.

Also, if u want you can contribute to this library.

On Sep 14, 2018 10:44, "Keshav Bhusal" <notifications@github.com> wrote:

but how to change the color of setHighlightedDays().

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/keyrunHORNET/date_picker_converter/issues/6#issuecomment-421231422>,
or mute the thread
